---
project_root_path: "{{ lookup('ansible.builtin.pipe', 'git rev-parse --show-toplevel' ) }}"
git_repositories_path: "{{ project_root_path }}/.git_repositories"
secrets_path: "{{ project_root_path }}/personal_ansible_secrets"
