---
python_scripts:
  - scripts/organize_documents/organize_documents.py
  - scripts/tools/pdf_to_text.py

git_repositories:
  - repo: https://github.com/majutsushi/urxvt-font-size
    dest: urxvt
  - repo: https://github.com/altercation/solarized
    dest: vim
  - repo: https://github.com/junegunn/vim-plug
    dest: vim
  - repo: https://github.com/nhdaly/tmux-better-mouse-mode
    dest: tmux
  - repo: https://github.com/tmux-plugins/tmux-sensible
    dest: tmux
  - repo: https://github.com/tmux-plugins/tpm
    dest: tmux
  - repo: https://github.com/cykerway/complete-alias
    dest: bash
  - repo: https://github.com/jonmosco/kube-ps1
    dest: bash
  - repo: https://github.com/so-fancy/diff-so-fancy
    dest: git

git_files:
  - src: urxvt/urxvt-font-size/font-size
    dest: .urxvt/ext/font-size
  - src: vim/solarized/vim-colors-solarized/colors/solarized.vim
    dest: .vim/colors/solarized.vim
    root_use: true
  - src: vim/vim-plug/plug.vim
    dest: .vim/autoload/plug.vim
    root_use: true
  - src: tmux
    dest: .tmux/plugins
    root_use: true

config_files:
  - src: .bashrc
    root_use: true
    backup: true
  - src: .bashrc.j2
    dest: .bashrc.ansible
    kind: template
  - src: .vimrc
    root_use: true
  - src: .gitconfig
  - src: .tmux.conf
  - src: .screenrc
  - src: terminator/config
    dest: .config/terminator/config
  - src: &item1 .moc/config
    dest: *item1
  - src: &item2 .moc/themes/custom_theme
    dest: *item2
  - src: .Xdefaults
  - src: xdefaults
    dest: .config/xdefaults
  - src: &item3 .urxvt/ext/clipboard
    dest: *item3
  - src: &item4 .urxvt/ext/tabbed-custom
    dest: *item4

common_scripts:
  - src: git/git_clean_local_branches.sh

etc_hosts:
  - ip: 192.168.106.100
    names:
      - nas

nas_volume_passwords_path: /root/.nas-volume-passwords
nas_credentials_path: /root/.nas-cred

setup_automounts:
  - src: //nas
    name: nas
    type: cifs
    credentials_file: "{{ nas_credentials_path }}"
    mount_options:
      - rw
      - uid=1000
      - gid=1000
    mounts:
      - name: media
        src: JIBUX-MEDIA
      - name: archives
        src: JIBUX-ARCHIVES
      - name: data
        src: JIBUX-DATA
        pre_mount_service:
          name: unlock-synology-volume
          argument: JIBUX-DATA
      - name: family
        src: JIBUX-FAMILY
        pre_mount_service:
          name: unlock-synology-volume
          argument: JIBUX-FAMILY
      - name: agathe
        src: AGATHE
        pre_mount_service:
          name: unlock-synology-volume
          argument: AGATHE
      - name: test
        src: Test
        idle_timeout: 10
        pre_mount_service:
          name: unlock-synology-volume
          argument: Test
