---
python_scripts:
  - scripts/organize_documents/organize_documents.py
  - scripts/tools/pdf_to_text.py

remote_files:
  - url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: .vim/autoload/plug.vim
    root_use: true
  - url: https://raw.githubusercontent.com/altercation/solarized/master/vim-colors-solarized/colors/solarized.vim
    dest: .vim/colors/solarized.vim
    root_use: true
  - url: https://raw.githubusercontent.com/cykerway/complete-alias/master/complete_alias
    dest: .bashrc.d/complete-alias
  - url: https://raw.githubusercontent.com/jonmosco/kube-ps1/master/kube-ps1.sh
    dest: .bashrc.d/kube-ps1.sh
  - url: https://github.com/so-fancy/diff-so-fancy/releases/download/v1.4.10/diff-so-fancy
    dest: .local/bin/diff-so-fancy
    mode: "0700"

git_repositories:
  - repo: https://github.com/majutsushi/urxvt-font-size
    dest: urxvt
  - repo: https://github.com/tmux-plugins/tpm
    dest: tmux

git_files:
  - src: urxvt/urxvt-font-size/font-size
    dest: .urxvt/ext/font-size
  - src: tmux/tpm
    dest: .tmux/plugins/tpm
    root_use: true

config_files:
  - src: .bashrc
    root_use: true
    backup: true
  - src: .bashrc.j2
    dest: .bashrc.ansible
    kind: template
  - src: .vimrc
    root_use: true
  - src: .gitconfig
  - src: .tmux.conf
  - src: .screenrc
  - src: terminator/config
    dest: .config/terminator/config
  - src: &item1 .moc/config
    dest: *item1
  - src: &item2 .moc/themes/custom_theme
    dest: *item2
  - src: .Xdefaults
  - src: xdefaults
    dest: .config/xdefaults
  - src: &item3 .urxvt/ext/clipboard
    dest: *item3
  - src: &item4 .urxvt/ext/tabbed-custom
    dest: *item4

common_scripts:
  - src: git/git_clean_local_branches.sh
  - src: misc/wake-up_nas.sh

etc_hosts:
  - ip: 192.168.106.100
    names:
      - nas

setup_automounts:
  - src: //nas
    name: nas
    type: cifs
    credentials_file: "{{ nas_credentials_path }}"
    mount_timeout: 300
    mount_options:
      - rw
      - uid=1000
      - gid=1000
    mounts:
      - name: media
        src: JIBUX-MEDIA
        pre_mount_service:
          name: wake-up-nas-and-wait-for-it
      - name: data
        src: JIBUX-DATA
        pre_mount_service:
          name: unlock-synology-share
          argument: JIBUX-DATA
      - name: pictures
        src: JIBUX-PICTURES
        pre_mount_service:
          name: unlock-synology-share
          argument: JIBUX-PICTURES

nas_credentials_path: /root/.nas-cred
nas_ssl_no_verify: true
