---
- name: Configure {{ mount_item.src }} to {{ mount_item.dest }}
  ansible.posix.mount:
    src: "{{ mount_item.src }}"
    path: "{{ mount_item.dest }}"
    fstype: "{{ mount_item.fstype|d('ext4') }}"
    state: "{{ mount_item.state|d('mounted') }}"
    passno: "{{ mount_item.passno|d(2) }}"
