---
- name: Add apt.syncthing.net repo
  deb822_repository:
    name: syncthing
    types: deb
    uris: https://apt.syncthing.net/
    suites: syncthing
    components: stable-v2
    signed_by: https://syncthing.net/release-key.gpg
    state: present

- name: Install syncthing
  ansible.builtin.apt:
    name: syncthing
    state: latest
    update_cache: true
