---
- name: Add docker repo
  deb822_repository:
    name: docker
    types: deb
    architectures: amd64
    uris: https://download.docker.com/linux/ubuntu
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable

- name: Install softwares
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
