- name: Install apt packages
  apt:
    name: "{{ apt_packages + (apt_desktop_packages if 'desktop' in group_names else []) }}"
    state: latest
    update_cache: true

- include_tasks:
    file: install_brews.yml
    apply:
      tags:
        - brew
  tags:
      - brew

- become: false
  block:
    - include_tasks:
        file: rust.yml
        apply:
          tags:
            - rust
      tags:
          - rust

- name: Clean
  apt:
    autoclean: true

- name: Autoremove
  apt:
    autoremove: true
