---
- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    state: latest
    update_cache: true

- name: Install apt packages for linux desktop
  apt:
    name: "{{ apt_linux_desktop_packages }}"
    state: latest
  when: "'linux_desktop' in group_names"

- name: Install apt packages for wsl
  apt:
    name: "{{ apt_wsl_packages }}"
    state: latest
  when: "'wsl' in group_names"

- include_tasks:
    file: install_brews.yml
    apply:
      tags:
        - brew
  tags:
      - brew

- include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker
  tags:
      - docker

- become: false
  block:
    - include_tasks:
        file: rust.yml
        apply:
          tags:
            - rust
      tags:
          - rust

- name: Clean
  apt:
    autoclean: true

- name: Autoremove
  apt:
    autoremove: true
