---
- name: Setup autofs for {{ autofs_item.name }}
  template:
    src: auto.name.j2
    dest: "/etc/auto.{{ autofs_item.name }}"
    mode: "0400"
    owner: root
    group: root
  notify:
    - Restart autofs

- name: Copy credentials file
  copy:
    src: "{{ autofs_item.credentials.src }}"
    dest: "{{ autofs_item.credentials.dest }}"
    mode: 0400
  no_log: true
