---
- name: Purge firefox
  ansible.builtin.apt:
    name: firefox
    state: absent
    purge: true

- name: Purge thunderbird
  ansible.builtin.apt:
    name: thunderbird
    state: absent
    purge: true
