---
- include_tasks:
    file: get_remote_file.yml
  vars:
    file_path: "{{ local_user_home }}/{{ remote_file.dest }}"
    file_dir_path: "{{ (local_user_home + '/' + remote_file.dest)|dirname }}"

- when: become_password_set
  become: true
  block:
    - include_tasks:
        file: get_remote_file.yml
      vars:
        file_path: "/root/{{ remote_file.dest }}"
        file_dir_path: "{{ ('/root/' + remote_file.dest)|dirname }}"
