---
- name: Import NAS credentials
  include_vars:
    file: "{{ secrets_path }}/nas/credentials.yml"
    name: nas_credentials

- name: Create synology_scripts_path dir
  file:
    path: "{{ synology_scripts_path }}"
    state: directory
    owner: root
    group: "{{ local_user_name }}"
    mode: "0750"
  tags:
    - scripts

- name: Credential files
  copy:
    dest: "{{ nas_credentials_path }}"
    owner: root
    group: root
    mode: "0400"
    content: |
      username={{ nas_credentials.jibux.username }}
      password={{ nas_credentials.jibux.password }}
  no_log: "{{ secure_log|d(true)|bool }}"

- name: Credential files (admin)
  copy:
    dest: "{{ nas_admin_credentials_path }}"
    owner: root
    group: "{{ local_user_name }}"
    mode: "0440"
    content: |
      username={{ nas_credentials.admin.username }}
      password={{ nas_credentials.admin.password }}
  no_log: "{{ secure_log|d(true)|bool }}"

- name: Share passwords
  copy:
    src: "{{ secrets_path }}/nas/share-passwords"
    dest: "{{ nas_share_passwords_path }}"
    owner: root
    group: "{{ local_user_name }}"
    mode: "0440"
  no_log: "{{ secure_log|d(true)|bool }}"

- name: Unlock wake up nas systemd service file
  template:
    src: wake-up-nas-and-wait-for-it.service
    dest: "{{ systemd_files_path }}/wake-up-nas-and-wait-for-it.service"
    owner: root
    group: root
    mode: "0444"
  notify: Daemon reload
  tags:
    - systemd

- name: Unlock synology share systemd service file
  template:
    src: unlock-synology-share@.service
    dest: "{{ systemd_files_path }}/unlock-synology-share@.service"
    owner: root
    group: root
    mode: "0444"
  notify: Daemon reload
  tags:
    - systemd

- name: manage-synology-nas script
  copy:
    src: manage-synology-nas.py
    dest: "{{ manage_synology_nas_script }}"
    owner: root
    group: "{{ local_user_name }}"
    mode: "0550"
  tags:
    - scripts

- name: Copy manage-synology-nas requirements.txt
  copy:
    src: manage-synology-nas_requirements.txt
    dest: "{{ synology_scripts_path }}/requirements.txt"
    owner: root
    group: root
    mode: "0400"
  tags:
    - venv

- set_fact:
    uv_bin_path: "{{ local_user_home }}/.local/bin/uv"
  become: false
  tags:
    - venv

- name: Setup venv
  command: "{{ uv_bin_path }} venv --directory '{{ synology_scripts_path }}' --python 3.12 --clear"
  tags:
    - venv

- name: Install script dependencies
  command: "{{ uv_bin_path }} pip install -r '{{ synology_scripts_path }}/requirements.txt' --directory '{{ synology_scripts_path }}'"
  tags:
    - venv
