---
nas_credentials_path: /root/.nas-cred
synology_scripts_path: /opt/synology_scripts
nas_admin_credentials_path: "{{ synology_scripts_path }}/.nas-cred"
nas_share_passwords_path: "{{ synology_scripts_path }}/.nas-share-passwords"
nas_ssl_no_verify: false
manage_synology_nas_script: "{{ synology_scripts_path }}/manage-synology-nas.py"
manage_synology_nas_python: "{{ synology_scripts_path }}/.venv/bin/python3"
