---
synology_scripts_path: /opt/synology_scripts
unlock_synology_volume_script: "{{ synology_scripts_path }}/unlock-synology-volume.py"
unlock_synology_volume_python: "{{ synology_scripts_path }}/.venv/bin/python3"
nas_volume_passwords_path: /root/.nas-volume-passwords
nas_credentials_path: /root/.nas-cred
